### ISSUE TITLE
I directly input the UV texture image, how should I modify the code?

### ISSUE THREAD

**Issue by seawater668** [VinAIResearch/CPM#23]

**Comment by thaoshibe** [comment]
Hi, you should modify the code from [Line34](https://github.com/VinAIResearch/CPM/blob/b12e83f195f6c3d378b93bb62da2fcdeb52f1312/main.py#L34)

Line 34-36: Get UV texture image of imageA and imageB. If you want to directly input the UV texture, please comment L34-36.

**Comment by seawater668** [comment]
Traceback (most recent call last):
  File "main.py", line 58, in <module>
    output = model.render_texture(new_txt)
  File "/data/hjq/CPM/makeup.py", line 132, in render_texture
    self.triangles.T,
AttributeError: 'Makeup' object has no attribute 'triangles'

**Comment by seawater668** [comment]
@thaoshibe 
if __name__ == "__main__":
    args = get_args()
    model = Makeup(args)

    imgA = np.array(Image.open(args.input))
    imgB = np.array(Image.open(args.style))
    imgA = cv2.resize(imgA, (256, 256))
    imgB = cv2.resize(imgB, (256, 256))
    A_txt = imgA.copy()
    B_txt = imgB.copy()
    # model.prn_process(imgA)
    # A_txt = model.get_texture()
    # B_txt = model.prn_process_target(imgB)
    if args.color_only:
        output = color_makeup(A_txt, B_txt, args.alpha)
    elif args.pattern_only:
        output = pattern_makeup(A_txt, B_txt)
    else:
        color_txt = model.makeup(A_txt, B_txt) * 255

        cv2.imwrite('./0929/color_txt.jpg', color_txt)
        mask = model.get_mask(B_txt)
        mask = (mask > 0.001).astype("uint8")
        cv2.imwrite('./0929/mask.jpg', mask)
        new_txt = color_txt * (1 - mask)[:, :, np.newaxis] + B_txt * mask[:, :, np.newaxis]
        cv2.imwrite('./0929/new_txt.jpg', new_txt)
        output = model.render_texture(new_txt)
        output = model.blend_imgs(model.face, output, alpha=1)

    x2, y2, x1, y1 = model.location_to_crop()
    output = np.concatenate([imgB[x2:], model.face[x2:], output[x2:]], axis=1)
    if not os.path.exists(args.savedir):
        os.makedirs(args.savedir)
    save_path = os.path.join(args.savedir, "result.png")

    Image.fromarray((output).astype("uint8")).save(save_path)
    print("Completed 👍 Please check result in: {}".format(save_path))

**Comment by thaoshibe** [comment]
As mentioned above: Sorry I can't assist you further. But if you want to modify anything, starting debug from [here](https://github.com/VinAIResearch/CPM/blob/b12e83f195f6c3d378b93bb62da2fcdeb52f1312/main.py#L34) is a good start.
Thank you!.
