### ISSUE TITLE
AttributeError: module 'segmentation_models_pytorch' has no attribute 'utils'

### ISSUE THREAD

**Issue by trproto** [VinAIResearch/CPM#24]
After following the install instructions and running the main.py script as instructed both locally and in colab...

>os.chdir(path)
>!python -W ignore main.py --style ./imgs/style-1.png --input ./imgs/non-makeup.png

I get the following error:

>Traceback (most recent call last):
  File "main.py", line 28, in <module>
    model = Makeup(args)
  File "/content/gdrive/.shortcut-targets-by-id/1rZyAvaAtqZ9a0okVcv4OFaq9aiVvKg5Q/CPM/makeup.py", line 18, in __init__
    self.pattern = Segmentor(args)
  File "/content/gdrive/.shortcut-targets-by-id/1rZyAvaAtqZ9a0okVcv4OFaq9aiVvKg5Q/CPM/utils/models.py", line 15, in __init__
    self.loss = smp.utils.losses.DiceLoss()
AttributeError: module 'segmentation_models_pytorch' has no attribute 'utils'

**Comment by trproto** [comment]
In *enviroment.yml* change line 169:

>   - segmentation-models-pytorch

to

>    - segmentation-models-pytorch==0.2

then reinstall environment.
